### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by rideralberta** [websharks/quick-cache#389] opened 2015-01-03 21:26 UTC
In the WordPress Post window, there is a message to update Quick Cache. When I select it, I am taken to the QC plugin window where I enter my username and password. This takes me, then, to the plugin update window of Wordpress. However, after proceeding to update, I get the message that the plugin is already at the current version—and it's not. 

Suggestions?

**Comment by jaswsinc** [comment] 2015-01-04 04:10
What version of Quick Cache Pro are you currently running please?

**Comment by rideralberta** [comment] 2015-01-04 04:25
Version 141205

Mark
____________________
www.markmallett.com <http://www.markmallett.com/>

**Comment by jaswsinc** [comment] 2015-01-04 05:26
Thank you. I'm making an attempt to reproduce this now.

**Comment by jaswsinc** [comment] 2015-01-04 06:01
Just tested this against WordPress v4.1 where I upgraded from Quick Cache Pro v141205 to v141231 without issue. What version of WordPress are you running please?

**Comment by rideralberta** [comment] 2015-01-04 06:09
I’m using 4.1 

Here’s are the steps:

1. At the top of Wordpress, I get the notification: "Quick Cache Pro: a new version is now available. Please upgrade to v141231 <http://www.markmallett.com/blog/wp-admin/admin.php?page=quick_cache-update-sync>.”

2. When I click the upgrade, it takes me to your QuickCache Updater within Wordpress, where I enter my WebSharks Username/Password. This then takes me to WordPress’s Update Plugin page where I enter my FTP username/password. After I click proceed, I get the notification "The plugin is at the latest version."

Mark
____________________
www.markmallett.com <http://www.markmallett.com/>

**Comment by jaswsinc** [comment] 2015-01-04 08:19
> his then takes me to WordPress’s Update Plugin page where I enter my FTP username/password.

I see. So you're using FTP or SFTP via WordPress to perform the updates as opposed to direct file access. This could be the point that I'm missing in my tests. Taking a closer look.

**Comment by jaswsinc** [comment] 2015-01-04 09:28
Referencing: http://codex.wordpress.org/Editing_wp-config.php#WordPress_Upgrade_Constants

**Comment by jaswsinc** [comment] 2015-01-04 09:44
Successfully reproduced the bug. Taking a closer look.

![2015-01-04_00-43-31](https://cloud.githubusercontent.com/assets/1563559/5605487/c1ec2c7e-93aa-11e4-8913-f3c6de6cc19c.png)

**Comment by jaswsinc** [comment] 2015-01-04 10:42
@rideralberta Thanks again for reporting this!

I've had the issue resolved in the development copy so that it won't be a problem moving forward. That change will be reviewed by our lead developer and included in the next release cycle.

In the mean time, you can work around the issue by specifying the FTP credentials that WordPress should use inside your `/wp-config.php` file; and this way you won't be bothered to enter them again when you're working inside the Dashboard.

Here are the lines that I added at the top of my `/wp-config.php` file to get this working...

```php
<?php
define( 'FS_METHOD', 'ftpext' );
define( 'FTP_BASE', '/public_html/jason/' );
define( 'FTP_USER', 'jason' );
define( 'FTP_PASS', 'xxxxxxxx' );
define( 'FTP_HOST', 'ftp.example.com' );
define( 'FTP_SSL', FALSE );
```

See also: http://codex.wordpress.org/Editing_wp-config.php#WordPress_Upgrade_Constants
~ For the full documentation regarding `FS_METHOD` and the `FTP_*` config values.

**Comment by rideralberta** [comment] 2015-01-04 20:14
Great, thank you!

**Comment by raamdev** [comment] 2015-01-04 20:37
@rideralberta Thanks so much for reporting this!

@jaswsinc Thanks for submitting the Pull Request!

This fix has been merged into the development trunk and will go out with the next public release.

---

_Note: If you're interested in testing a beta release of Quick Cache before the next version comes out, please sign-up to be a beta tester [here](http://www.websharks-inc.com/r/quick-cache-beta-testers-list/)._

**Comment by rideralberta** [comment] 2015-01-04 21:50
Thanks for thanking me and each other!

;-)

Mark
____________________
www.markmallett.com <http://www.markmallett.com/>

**Comment by rideralberta** [comment] 2015-01-05 01:09
Hm. We made these changes, and the plugin appeared to update… but when it tried to return me to the Admin page, it was blank, as well as the entire blog—just a blank page being served up. The cache appears to be broken all of a sudden…

Mark
____________________
www.markmallett.com <http://www.markmallett.com/>

**Comment by jaswsinc** [comment] 2015-01-06 13:46
> but when it tried to return me to the Admin page, it was blank, as well as the entire blog—just a blank page being served up. The cache appears to be broken all of a sudden…

Oh goodness! Not sure why that would have happened. You may want to seek assistance from your hosting company in this case. Have you lost all access to your Dashboard now?

---

##### EMERGENCY: If All Else Fails (How-To Remove Quick Cache)
Ordinarily you can just deactivate Quick Cache from the plugins menu in WordPress. However, if you're having a more serious issue, please follow the instructions here.

- Log into your site via FTP; perhaps using [FileZilla](http://www.youtube.com/watch?v=joXUMhr8PhU).
- Delete this file: `/wp-content/advanced-cache.php`
- Delete this directory: `/wp-content/plugins/quick-cache/`
- Remove this line from your `/wp-config.php` file: `define('WP_CACHE', TRUE);`

Quick Cache is now completely uninstalled and you can start fresh :-)

----

If you start fresh and the problem continues, please report back and let us know about this.

----

NOTE: If you added any of the config. values that I mentioned previously and these are somehow corrupted on your end, that could be a problem too. So you might want to review those carefully before proceeding any further. For instance, make sure you are not missing any of the single quotes seen in this example.

```php
<?php
define( 'FS_METHOD', 'ftpext' );
define( 'FTP_BASE', '/public_html/jason/' );
define( 'FTP_USER', 'jason' );
define( 'FTP_PASS', 'xxxxxxxx' );
define( 'FTP_HOST', 'ftp.example.com' );
define( 'FTP_SSL', FALSE );
```

**Comment by raamdev** [comment] 2015-01-06 13:50
@jaswsinc Thanks for jumping in here. :)

@rideralberta I'm going to mark this Issue as closed, but if you discover there's still a problem after following Jason's suggestions above, and you suspect it has something to do with Jason's suggestion, please let us know and I'll reopen this.

**Closed by raamdev** 2015-01-06 13:50 UTC
Labels: bug, Pro

**Comment by rideralberta** [comment] 2015-01-06 15:46
Hi Jason,

My host restored an earlier backup, thank goodness. They felt it was an issue on your side now. So, I manually installed your latest version and deleted the old one. I don’t know if that’s the proper procedure, but it seems to be working. 

I guess I’ll wait for a future release from you that will have this fixed. Thanks again. 

Mark
____________________
www.markmallett.com <http://www.markmallett.com/>

**Comment by jaswsinc** [comment] 2015-01-06 15:48
@rideralberta Interesting. We have not had any other reports of problems like this with the latest release. Was there any indication of what the problem was exactly? Can you find anything in your PHP error log?

**Comment by rideralberta** [comment] 2015-01-06 15:50
I’ll fire that question off to my host. 

Mark
____________________
www.markmallett.com <http://www.markmallett.com/>

**Comment by rideralberta** [comment] 2015-01-07 06:32
Hi Jason,

This was my host’s reply: "Unfortunately, there were no errors generated in the error log when attempting to go to the blog and seeing the blank white page.”

Mark
____________________
www.markmallett.com <http://www.markmallett.com/>

**Comment by raamdev** [comment] 2015-01-08 15:18
@rideralberta You may want to enable WordPress Debugging prior to doing the next Quick Cache update, just so that _if_ the update fails again, you'll have a better chance at figuring out _why_ it's failing:

---

Add the following lines to your `wp-config.php` file then run the auto-update mechanism and check the `wp-content/debug.log` file for any errors:

```
define('WP_DEBUG', true); // enables debugging
define('WP_DEBUG_LOG', true); // logs messages to wp-content/debug.log
define('WP_DEBUG_DISPLAY', false); // hides debug messages from showing in the browser
```

See also: https://codex.wordpress.org/Debugging_in_WordPress

---

As Jason mentioned, we have not seen this issue from any other Quick Cache Pro users, and we know there are thousands of successful updates every time an update is released, so there's a good chance this was either an unreproducible fluke, or there's a weird configuration on your server that's causing this (assuming it can be reproduced).

I'll leave this Issue closed for now, but if you do find errors during the next update, please reply here so  that we can reopen this.

**Comment by raamdev** [comment] 2015-01-30 02:19
The fixes applied from this issue have been released today with v150129:

- **Bug Fix** (Pro): Fixed a bug where the Pro Updater would fail when FTP or SFTP details via the WordPress Dashboard are required to perform updates. Props @jaswsinc. See [#389](https://github.com/websharks/quick-cache/issues/389).

See the [v150129 announcement post](http://www.websharks-inc.com/post/quick-cache-v150129-now-available/).

---

This issue will now be locked to further updates. If you have something to add related to this Issue, please open a new GitHub Issue and mention this one (#389).
