### ISSUE TITLE
When access admin pages without changing anything, should not clear caches

### ISSUE THREAD

**Issue by KTS915** [websharks/quick-cache#393] opened 2015-01-05 23:25 UTC
I use QCP on membership sites with s2Member, and I have set it to maintain a separate cache for each user. Just in case it matters, I also have it set to cache GET requests (which is essential for my sites).

The issue I'm experiencing is that, as soon as I go into the admin pages, QCP reports that it has discovered a change and wipes every single member's cache. This means that, while all I wish to do is to view some information -- I am not changing anything -- every user's cache is cleared. 

I don't think any cache should be cleared, even the admin's, unless I actually change something.

**Comment by raamdev** [comment] 2015-01-06 13:26
@KTS915 This sounds like there might be some other plugin that you're running that is triggering an action (every time you load a WordPress Dashboard page) that Quick Cache detects as a trigger associated with "an important site change" and that results in the cache being wiped. 

If you disable all plugins except Quick Cache and s2Member, do you still experience this issue?

**Comment by KTS915** [comment] 2015-01-06 15:33
@Raam,

You are exactly right. It turns out that I have two plugins that both cause this behavior. One is WP Idle Logout, which is available here: https://wordpress.org/plugins/wp-idle-logout/

The other is Watu Pro. (The free version of Watu, which I was using before, does not cause this problem).

What's the best way to proceed from here? Do I approach the devs for these plugins? If so, is there any particular guidance I can give them on what they need to do? Or would you prefer to take a look first? (If so, let me know how I can send you a copy of Watu Pro.)

Thanks very much!

**Comment by raamdev** [comment] 2015-01-06 15:39
@KTS915 You should contact the developers of those plugins and ask them to look into providing compatibility with Quick Cache. We just hook into common WordPress actions and watch those to detect when a change takes place (such as changing the theme, or updating site options, or publishing a post) so that we can know when we should clear the cache. 

It sounds like those plugins are hooking into and triggering one of those actions as well, which makes Quick Cache clear the cache prematurely.

All of the Quick Cache source code is available for them to inspect, with all of the actions that Quick Cache attaches to available here: https://github.com/websharks/quick-cache/blob/000000-dev/quick-cache/quick-cache.inc.php#L258-L328

---

I'm going to close this issue for now, but feel free to reference this when contacting the other plugin developers. If they have any questions, I'd be happy to help with improving compatibility with Quick Cache.

**Closed by raamdev** 2015-01-06 15:39 UTC
Labels: needs feedback

**Comment by KTS915** [comment] 2015-01-06 16:18
Thanks very much. I have now contacted the Watu Pro developer. 

WP Idle Logout seems to have been abandoned, so I am going to look for an alternative.

**Comment by KTS915** [comment] 2015-01-06 16:28
This is the response from the Watu Pro developer:

"I checked all the 37 actions they use to define whether to clear the cache. We call none of these. Maybe it has something to do with visiting options-general.php but I don't know. Since I am not the author of the caching plugin I can't debug this further."

**Comment by jaswsinc** [comment] 2015-01-06 16:47
@KTS915 

I suspect that one of your plugins is calling upon a WordPress core routine that indirectly causes WordPress to fire off one of the hooks that Quick Cache is attached to for clearing the entire cache.

So the plugin developer may not realize it, but they could be indirectly triggering a wipe of the cache due to the WordPress core hooks being fired in succession under scenarios within a single process.

---

I just ran a quick test and did a review of the codebase for Watu (Lite) version. I was unable to reproduce it with Watu Lite version. A review of the codebase shows no issues that I can see.

Here is a list of hooks from the QCP source code that could trigger a full clearing of the cache; either directly or indirectly. See the notes below that start with `@attaches-to`.

```php
/**
			 * Automatically clears all cache files for the current blog.
			 *
			 * @attaches-to `switch_theme` hook.
			 *
			 * @attaches-to `wp_create_nav_menu` hook.
			 * @attaches-to `wp_update_nav_menu` hook.
			 * @attaches-to `wp_delete_nav_menu` hook.
			 *
			 * @attaches-to `create_term` hook.
			 * @attaches-to `edit_terms` hook.
			 * @attaches-to `delete_term` hook.
			 *
			 * @attaches-to `add_link` hook.
			 * @attaches-to `edit_link` hook.
			 * @attaches-to `delete_link` hook.
			 *
			 * @since 140422 First documented version.
			 *
			 * @return integer Total files cleared by this routine (if any).
			 *
			 * @note This is also called upon during plugin activation.
			 */
			public function auto_clear_cache()
			{
				$counter = 0; // Initialize.

				if(isset($this->cache[__FUNCTION__]))
					return $counter; // Already did this.
				$this->cache[__FUNCTION__] = -1;

				if(!$this->options['enable'])
					return $counter; // Nothing to do.

				if($this->disable_auto_clear_cache_routines())
					return $counter; // Nothing to do.

				$counter += $this->clear_cache();

				if($counter && is_admin() && $this->options['change_notifications_enable'])
					$this->enqueue_notice('<img src="'.esc_attr($this->url('/client-s/images/clear.png')).'" style="float:left; margin:0 10px 0 0; border:0;" />'.
					                      sprintf(__('<strong>Quick Cache:</strong> detected important site changes. Found %1$s in the cache for this site; auto-clearing.', $this->text_domain),
					                              esc_html($this->i18n_files($counter))));

				return apply_filters(__METHOD__, $counter, get_defined_vars());
			}
```

**Comment by KTS915** [comment] 2015-01-06 17:19
Thanks very much, Jason. Yes, the free Lite version isn't causing the issue.

I'll have a look at the Pro version, and see if I can find any of those hooks.

**Comment by KTS915** [comment] 2015-01-07 00:06
Well, it's been a journey, but I finally got there. I won't go through the whole story of how I found the true culprit, but I will identify it in case someone else experiences a similar problem.

The culprit was actually Plainview Activity Monitor. 

This was deactivated, but presumably its database entries were somehow interacting with Watu Pro and Idle Logout to cause QCP to clear the caches when I navigated to the admin pages. Now that I have cleared out all PAM's database entries, the other two plugins are causing no problems at all, and QCP is no longer clearing caches unexpectedly.

I don't know if this is anything like what Jason was referring to when he referred to indirect causes, but it's as indirect as I ever hope to experience! Anyway, thanks as always for all your help!

**Comment by raamdev** [comment] 2015-01-08 15:23
> This was deactivated, but presumably its database entries were somehow interacting with Watu Pro and Idle Logout to cause QCP to clear the caches when I navigated to the admin pages.
> [...]
> I don't know if this is anything like what Jason was referring to when he referred to indirect causes, but it's as indirect as I ever hope to experience!

@KTS915 Wow! That sounds like quite sneaky problem to solve! Thanks so much for posting your findings here. I've added a note to the [Troubleshooting Wiki Page](https://github.com/websharks/quick-cache/wiki/Troubleshooting#list-of-incompatible-plugins) regarding the Plainview Activity Monitor plugin.
